### ISSUE TITLE
Component.getId() not working in Python

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#190]
Hi all!

Could someone have a look at this branch:
https://github.com/MichaelClerx/libcellml/tree/issue161

And then build and run the tests in `build/src/bindings/python/test.py` (should be run from `build/src/bindings/python`).

Just to see if inheritance was working I tested `getId()` in `Entity`, `NamedEntity`, `ImportedEntity`, and `ComponentEntity`, but when I got to `Component` it stopped working. Can't see anything different.
Any help appreciated

**Comment by agarny** [comment]
Here is what I did:
 - Cloned your repository and checked out your `issue161` branch;
 - Configured CMake:
   - Rather than `LIBCELLML_PYTHON`, I would personally use `LIBCELLML_PYTHON_BINDING` to make it clearer what that Python thing is all about. (In fact, maybe we should use `LIBCELLML_BINDING_PYTHON`, so that whenever we support other bindings, they will be listed next to one another.)
   - `SWIG_EXECUTABLE` should only be visible in advanced mode.
 - Compiled libCellML, which resulted in quite a few warnings (I get the feeling that they might be 'expected'. Is that the case?):
```
[31/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:38: Warning 509: Overloaded method libcellml::Entity::Entity(libcellml::Entity &&) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:37: Warning 509: as it is shadowed by libcellml::Entity::Entity(libcellml::Entity const &).
[37/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/importedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/componententity.h:49: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/componententity.h:48: Warning 509: Overloaded method libcellml::ComponentEntity::ComponentEntity(libcellml::ComponentEntity const &) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/componententity.h:47: Warning 509: as it is shadowed by libcellml::ComponentEntity::ComponentEntity(libcellml::ComponentEntity &&).
[39/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:38: Warning 509: Overloaded method libcellml::NamedEntity::NamedEntity(libcellml::NamedEntity &&) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:37: Warning 509: as it is shadowed by libcellml::NamedEntity::NamedEntity(libcellml::NamedEntity const &).
[44/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/importedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/units.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/units.h:33: Warning 520: Base class 'libcellml::ImportedEntity' of 'Units' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/units.h:33: Warning 520: Base class 'libcellml::NamedEntity' of 'Units' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/units.h:33: Warning 520: Base class 'libcellml::Entity' of 'Units' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/units.h:38: Warning 509: Overloaded method libcellml::Units::Units(libcellml::Units &&) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/units.h:37: Warning 509: as it is shadowed by libcellml::Units::Units(libcellml::Units const &).
[46/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/importedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/importedentity.h:38: Warning 509: Overloaded method libcellml::ImportedEntity::ImportedEntity(libcellml::ImportedEntity &&) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/importedentity.h:37: Warning 509: as it is shadowed by libcellml::ImportedEntity::ImportedEntity(libcellml::ImportedEntity const &).
[47/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/import.h:36: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/import.h:30: Warning 520: Base class 'libcellml::Entity' of 'Import' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/import.h:35: Warning 509: Overloaded method libcellml::Import::Import(libcellml::Import &&) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/import.h:34: Warning 509: as it is shadowed by libcellml::Import::Import(libcellml::Import const &).
[54/80] Swig source
/Users/Alan/Desktop/libcellml/src/api/libcellml/entity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/namedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/importedentity.h:39: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/componententity.h:49: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:36: Warning 362: operator= ignored
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:30: Warning 520: Base class 'libcellml::ComponentEntity' of 'Component' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:30: Warning 520: Base class 'libcellml::ImportedEntity' of 'Component' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:30: Warning 520: Base class 'libcellml::NamedEntity' of 'Component' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:30: Warning 520: Base class 'libcellml::Entity' of 'Component' is not similarly marked as a smart pointer.
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:35: Warning 509: Overloaded method libcellml::Component::Component(libcellml::Component &&) effectively ignored,
/Users/Alan/Desktop/libcellml/src/api/libcellml/component.h:34: Warning 509: as it is shadowed by libcellml::Component::Component(libcellml::Component const &).
[80/80] Linking CXX executable tests/test_parser
```
 - Ran the test and got:
```
.E....
======================================================================
ERROR: test_component (test_component.TestComponent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Alan/Desktop/libcellml/build/src/bindings/python/tests/test_component.py", line 32, in test_component
    self.assertEqual(x.getId(), '')
  File "/Users/Alan/Desktop/libcellml/build/src/bindings/python/libcellml/entity.py", line 118, in getId
    return _entity.Entity_getId(self)
TypeError: in method 'Entity_getId', argument 1 of type 'libcellml::Entity const *'

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (errors=1)
```

So, I can confirm the issue you are having. From there, I tried a couple of things, but to no avail. You test that the component inherits from `Entity`, so it ought to be fine and yet...!? Your tests for `ComponentEntity` work fine and `Component` inherits from `ComponentEntity`.  So, it looks like that extra level of inheritance messes things up...?! Well, I am no Python expert, so I must confess that I am at a loss here...

**Comment by hsorby** [comment]
I have tried this also and find I cannot call the getId from any object in the hierarchy.  When I ran the tests I got:

```
.E....
======================================================================
ERROR: test_component (test_component.TestComponent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hsor001/work/cellml-software/libcellml-build-release/src/bindings/python/tests/test_component.py", line 32, in test_component
    self.assertEqual(x.getId(), '')
  File "/Users/hsor001/work/cellml-software/libcellml-build-release/src/bindings/python/libcellml/entity.py", line 113, in getId
    return _entity.Entity_getId(self)
TypeError: in method 'Entity_getId', argument 1 of type 'libcellml::Entity const *'

----------------------------------------------------------------------
Ran 6 tests in 0.013s

FAILED (errors=1)
```

but when I tried running the tests with nosetests I got:

```
E.E....
======================================================================
ERROR: Failure: NotImplementedError (Wrong number or type of arguments for overloaded function 'Units_getUnitAttributes'.
  Possible C/C++ prototypes are:
    libcellml::Units::getUnitAttributes(size_t,std::string &,std::string &,double &,double &) const
    libcellml::Units::getUnitAttributes(std::string const &,std::string &,double &,double &) const
    libcellml::Units::getUnitAttributes(libcellml::Units::StandardUnit,std::string &,double &,double &) const
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/hsor001/work/cellml-software/libcellml-build-release/src/bindings/python/test_libcellml.py", line 9, in <module>
    u.getUnitAttributes("bob")
  File "/Users/hsor001/work/cellml-software/libcellml-build-release/src/bindings/python/libcellml/units.py", line 157, in getUnitAttributes
    return _units.Units_getUnitAttributes(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Units_getUnitAttributes'.
  Possible C/C++ prototypes are:
    libcellml::Units::getUnitAttributes(size_t,std::string &,std::string &,double &,double &) const
    libcellml::Units::getUnitAttributes(std::string const &,std::string &,double &,double &) const
    libcellml::Units::getUnitAttributes(libcellml::Units::StandardUnit,std::string &,double &,double &) const


======================================================================
ERROR: test_component (test_component.TestComponent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hsor001/work/cellml-software/libcellml-build-release/src/bindings/python/tests/test_component.py", line 32, in test_component
    self.assertEqual(x.getId(), '')
  File "/Users/hsor001/work/cellml-software/libcellml-build-release/src/bindings/python/libcellml/entity.py", line 113, in getId
    return _entity.Entity_getId(self)
TypeError: in method 'Entity_getId', argument 1 of type 'libcellml::Entity const *'

----------------------------------------------------------------------
Ran 7 tests in 0.033s

FAILED (errors=2)
```

It seems nosetests found an extra test!

I'm thinking that the self parameter has not been wrapped properly currently investigating further.

**Comment by MichaelClerx** [comment]
Bit confused how the tests are passing if you can't call getId from other objects either!

**Comment by MichaelClerx** [comment]
Some of those warnings are expected but I'll look into the base class shared_ptr ones, thanks!

**Comment by MichaelClerx** [comment]
@hsorby not sure what you mean by 'nosetetst' !

**Comment by MichaelClerx** [comment]
Fixed now, thanks for the help!

**Comment by MichaelClerx** [comment]
@agarny Have updated the name to `LIBCELLML_BINDINGS_PYTHON`

But what do you mean by "SWIG_EXECUTABLE should only be visible in advanced mode."?

**Comment by agarny** [comment]
What I mean is that if you configure libCellML using, say, `ccmake` on Linux/macOS, then you will see `SWIG_EXECUTABLE` listed:

```
 LIBCELLML_BINDINGS_PYTHON       *ON                                                                                                                                                                  
 LIBCELLML_BUILD_SHARED          *ON                                                                                                                                                                  
 LIBCELLML_BUILD_TYPE            *Debug                                                                                                                                                               
 LIBCELLML_COVERAGE              *ON                                                                                                                                                                  
 LIBCELLML_INSTALL_PREFIX        */usr/local                                                                                                                                                          
 LIBCELLML_TREAT_WARNINGS_AS_ER  *ON                                                                                                                                                                  
 LIBCELLML_UNIT_TESTS            *ON                                                                                                                                                                  
 SWIG_EXECUTABLE                 */usr/local/bin/swig                                                                                                                                                 
```

while I would expect it to be listed only when in advanced mode (i.e. when pressing `t`), in the same way that `DOXYGEN_EXECUTABLE`, `SPHINX_EXECUTABLE`, etc. are listed only in that mode (see the call to `mark_as_advanced()` in [`cmake/environmentchecks.cmake`](https://github.com/cellml/libcellml/blob/develop/cmake/environmentchecks.cmake)).

The idea is that, in basic mode, you only see whatever is needed to configure libCellML itself.

**Comment by MichaelClerx** [comment]
Thanks! Will look into that
