### ISSUE TITLE
Javascript binding fails on Unit

### ISSUE THREAD

**Issue by Moop204** [cellml/libcellml#845]
Running any cellml file with 'Unit' element causes a crash. 

```
stoi: no conversion
undefined
RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
/home/moop204/Documents/uni/thesis/test/libcellml-test/node_modules/libcellml.js/libcellml.common.js:58
        throw ex 
        ^

RuntimeError: abort(RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/home/moop204/Documents/uni/thesis/test/libcellml-test/node_modules/libcellml.js/libcellml.common.js:224:7)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```
After reformatting libcellml.common I find that it fails in this bit of code:
```
if (ENVIRONMENT_IS_NODE) {
  if (ENVIRONMENT_IS_WORKER) {
    scriptDirectory = require("path").dirname(scriptDirectory) + "/";
  } else {
    scriptDirectory = __dirname + "/";
  }
  read_ = function shell_read(filename, binary) {
    if (!nodeFS) nodeFS = require("fs");
    if (!nodePath) nodePath = require("path");
    filename = nodePath["normalize"](filename);
    return nodeFS["readFileSync"](filename, binary ? null : "utf8");
  };

  readBinary = function readBinary(filename) {
    var ret = read_(filename, true);
    if (!ret.buffer) {
      ret = new Uint8Array(ret);
    }
    assert(ret.buffer);
    return ret;
  };

  if (process["argv"].length > 1) {
    thisProgram = process["argv"][1].replace(/\\/g, "/");
  }
  arguments_ = process["argv"].slice(2);
  process["on"]("uncaughtException", function (ex) {
    if (!(ex instanceof ExitStatus)) {
      throw ex; <-- HERE
    }
  });
  process["on"]("unhandledRejection", abort);
  quit_ = function (status) {
    process["exit"](status);
  };
  Module["inspect"] = function () {
    return "[Emscripten Module object]";
  };
}
```

Code run is:
```
const cellml = require('libcellml.js/libcellml.common');
cellml().then(libcellml=>{
    const p = new libcellml.Parser();
    const file = `<?xml version="1.0" encoding="UTF-8"?>
    <model xmlns="http://www.cellml.org/cellml/2.0#" xmlns:cellml="http://www.cellml.org/cellml/2.0#" xmlns:xlink="http://www.w3.org/1999/xlink" name="MyModel1" id="MyModel1">
        <units name="millisecond">
            <unit prefix="milli" units="second"/>
        </units>
    </model>`
    const m = p.parseModel(file);
    const v = new libcellml.Validator();
    v.validateModel(m);
    console.log(v.errorCount());
})
```

**Comment by hsorby** [comment]
Unfortunately web assembly cannot handle exceptions at this time and the libcellml library does trigger some on occasion.  In this case I have improved the web assembly parsing of Units but if you use a non-numeric units prefix (as in this case) then currently we trigger an exception.

**Comment by hsorby** [comment]
We could rework the Units handling to try harder to avoid triggering the exception.

**Comment by hsorby** [comment]
In other places if you trigger an exception it is because the model is badly formed and this is much less likely to happen than this Units problem.

**Comment by hsorby** [comment]
Hi @Moop204 we have made changes to the codebase.  Now if you build the bindings with the updated code this issue should be resolved.

If you could try out the changes and report back here that would be great thanks.

Simply closing this issue will be taken to mean that the changes work for you.

**Comment by Moop204** [comment]
Hi @hsorby I have tried running the old libcellml with the suggested numeric units and it worked great. 

I've been trying to build the js bindings but there are some build errors around the 'Unit' related functions in the annotator class. 

```
[ 58%] Building CXX object src/bindings/javascript/CMakeFiles/javascript-bindings.dir/annotator.cpp.o
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:36:66: error: expected expression
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &, size_t)>(&libcellml::Annotator::unit))
                                                                 ^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:36:87: error: unexpected type name 'size_t': expected expression
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &, size_t)>(&libcellml::Annotator::unit))
                                                                                      ^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:36:58: error: no member named 'UnitPtr' in namespace 'libcellml'
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &, size_t)>(&libcellml::Annotator::unit))
                                              ~~~~~~~~~~~^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:36:97: error: no member named 'unit' in 'libcellml::Annotator'; did you mean 'exit'?
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &, size_t)>(&libcellml::Annotator::unit))
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                exit
/home/moop204/apps/emscripten/emsdk/upstream/emscripten/cache/sysroot/include/stdlib.h:46:16: note: 'exit' declared here
_Noreturn void exit (int);
               ^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:37:66: error: expected expression
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &)>(&libcellml::Annotator::unit))
                                                                 ^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:37:58: error: no member named 'UnitPtr' in namespace 'libcellml'
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &)>(&libcellml::Annotator::unit))
                                              ~~~~~~~~~~~^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:37:89: error: no member named 'unit' in 'libcellml::Annotator'; did you mean 'exit'?
        .function("unitById", select_overload<libcellml::UnitPtr(const std::string &)>(&libcellml::Annotator::unit))
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                        exit
/home/moop204/apps/emscripten/emsdk/upstream/emscripten/cache/sysroot/include/stdlib.h:46:16: note: 'exit' declared here
_Noreturn void exit (int);
               ^
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp:57:86: error: no type named 'UnitPtr' in namespace 'libcellml'; did you mean 'UnitsPtr'?
        .function("assignIdByUnitItem", select_overload<std::string(const libcellml::UnitPtr &)>(&libcellml::Annotator::assignId))
                                                                          ~~~~~~~~~~~^~~~~~~
                                                                                     UnitsPtr
/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/api/libcellml/types.h:81:7: note: 'UnitsPtr' declared here
using UnitsPtr = std::shared_ptr<Units>; /**< Type definition for shared units pointer. */
      ^
8 errors generated.
em++: error: '/home/moop204/apps/emscripten/emsdk/upstream/bin/clang++ -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -iwithsysroot/include/SDL -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration --sysroot=/home/moop204/apps/emscripten/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DLIBXML_STATIC -I/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/build-libcellml-release/src/api -I/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/api -I/home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/api/libcellml/module -isystem /home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/usr/local/include/libxml2 -isystem /home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/usr/local/include -O3 -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=gnu++17 -c /home/moop204/Documents/uni/thesis/libcellml-issues/emscripten/libcellml/src/bindings/javascript/annotator.cpp -o CMakeFiles/javascript-bindings.dir/annotator.cpp.o' failed (1)
src/bindings/javascript/CMakeFiles/javascript-bindings.dir/build.make:166: recipe for target 'src/bindings/javascript/CMakeFiles/javascript-bindings.dir/annotator.cpp.o' failed
make[2]: *** [src/bindings/javascript/CMakeFiles/javascript-bindings.dir/annotator.cpp.o] Error 1
CMakeFiles/Makefile2:358: recipe for target 'src/bindings/javascript/CMakeFiles/javascript-bindings.dir/all' failed
make[1]: *** [src/bindings/javascript/CMakeFiles/javascript-bindings.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
```

I followed the instructions [here](https://github.com/cellml/libcellml/blob/main/docs/dev_building_web_assembly.rst).

**Comment by hsorby** [comment]
Ahh, we have changed some of the API and not updated the javascript bindings.  We don't yet have the javascript bindings as part of our CI setup so we can probably expect more of these types of issues for a little while.  I'll try and fix it.

**Comment by hsorby** [comment]
Hopefully the build errors are fixed now.

Again let us know how things turned out or simply close this issue if you are happy with the result on this issue.
