### ISSUE TITLE
Unable to use .parent() with js bindings

### ISSUE THREAD

**Issue by Moop204** [cellml/libcellml#863]
Whenever parent function is called (tested on Component and Variable) it generates the same UnboundTypeError. This may be related to this [empscripten issue](https://github.com/emscripten-core/emscripten/issues/4475). 

Resulting Error Message
```
UnboundTypeError: Cannot call ParentedEntity.parent due to unbound types: NSt3__210shared_ptrIN9libcellml14ParentedEntityEEE

      62 |   if (component.hasParent()) {
      63 |     parentType = Elements.component;
    > 64 |     parentElement = component.parent();
         |                               ^
      65 |   }
```
Call Stack
```
      at UnboundTypeError.<anonymous> (node_modules/libcellml.js/libcellml.common.js:9:91480)
      at new UnboundTypeError (eval at createNamedFunction (node_modules/libcellml.js/libcellml.common.js:9:91189), <anonymous>:2:34)
      at throwUnboundTypeError (node_modules/libcellml.js/libcellml.common.js:9:108466)
      at Component.parent (node_modules/libcellml.js/libcellml.common.js:9:117253)
      at convertComponent (src/utility/Converter.ts:64:31)
      at _callee5$ (src/__tests__/Converter.test.tsx:120:30)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by hsorby** [comment]
I will investigate this, hopefully just something that I have forgotten.
